version: '3.8'

services:
  html-go-express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: html-go-express
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - html-go-data:/usr/src/app/data
      - html-go-sessions:/usr/src/app/sessions
      - html-go-db:/usr/src/app/db
    environment:
      - NODE_ENV=production
      - PORT=8888
      - HOST=0.0.0.0
      - AUTH_ENABLED=true
      - AUTH_PASSWORD=admin123  # 向后兼容，作为管理员密码，➡️所有密码请改为安全密码
      - ADMIN_PASSWORD=admin123  # 管理员密码（完全权限）
      - USER_PASSWORD=user123  # 普通用户密码（只能发布HTML）
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8888/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - html-go-network

volumes:
  html-go-data:
    driver: local
  html-go-sessions:
    driver: local
  html-go-db:
    driver: local

networks:
  html-go-network:
    driver: bridge
